
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BddoServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface BddoServiceSoap {

	/**
	 * 
	 * @param xmlData
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Invoker", action = "http://tempuri.org/Invoker")
	@WebResult(name = "InvokerResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Invoker", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Invoker")
	@ResponseWrapper(localName = "InvokerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InvokerResponse")
	public String invoker(@WebParam(name = "xmlData", targetNamespace = "http://tempuri.org/") String xmlData);

	/**
	 * Alta y/o Modificaci�n de Empleados
	 * 
	 * @param pSectionName
	 * @param pIdUser
	 * @param pSheetNumber
	 * @param pCitizenShip
	 * @param pCuit
	 * @param pSubsidiaryName
	 * @param pIdEmployeeSexType
	 * @param pRol
	 * @param pCuil
	 * @param token
	 * @param pCitizenshipDocumentNumber
	 * @param pEmail
	 * @param pFirstName
	 * @param pIdEmployeeCitizenshipDocType
	 * @param pAddress
	 * @param pDateEntry
	 * @param pLastName
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/employeeAdd")
	@WebResult(name = "employeeAddResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "employeeAdd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmployeeAdd")
	@ResponseWrapper(localName = "employeeAddResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmployeeAddResponse")
	public String employeeAdd(@WebParam(name = "pIdUser", targetNamespace = "http://tempuri.org/") String pIdUser,
			@WebParam(name = "pCuit", targetNamespace = "http://tempuri.org/") String pCuit,
			@WebParam(name = "pSectionName", targetNamespace = "http://tempuri.org/") String pSectionName,
			@WebParam(name = "pSubsidiaryName", targetNamespace = "http://tempuri.org/") String pSubsidiaryName,
			@WebParam(name = "pSheetNumber", targetNamespace = "http://tempuri.org/") String pSheetNumber,
			@WebParam(name = "pCuil", targetNamespace = "http://tempuri.org/") String pCuil,
			@WebParam(name = "pCitizenShip", targetNamespace = "http://tempuri.org/") String pCitizenShip,
			@WebParam(name = "pIdEmployeeSexType", targetNamespace = "http://tempuri.org/") String pIdEmployeeSexType,
			@WebParam(name = "pIdEmployeeCitizenshipDocType", targetNamespace = "http://tempuri.org/") String pIdEmployeeCitizenshipDocType,
			@WebParam(name = "pCitizenshipDocumentNumber", targetNamespace = "http://tempuri.org/") String pCitizenshipDocumentNumber,
			@WebParam(name = "pDateEntry", targetNamespace = "http://tempuri.org/") String pDateEntry,
			@WebParam(name = "pFirstName", targetNamespace = "http://tempuri.org/") String pFirstName,
			@WebParam(name = "pLastName", targetNamespace = "http://tempuri.org/") String pLastName,
			@WebParam(name = "pRol", targetNamespace = "http://tempuri.org/") String pRol,
			@WebParam(name = "pEmail", targetNamespace = "http://tempuri.org/") String pEmail,
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "pAddress", targetNamespace = "http://tempuri.org/") String pAddress);

	/**
	 * Obtener documento por empleado
	 * 
	 * @param pXmlSolicitud
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetEmployeeInboxes", action = "http://tempuri.org/GetEmployeeInboxes")
	@WebResult(name = "GetEmployeeInboxesResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetEmployeeInboxes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeInboxes")
	@ResponseWrapper(localName = "GetEmployeeInboxesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmployeeInboxesResponse")
	public String getEmployeeInboxes(
			@WebParam(name = "pXmlSolicitud", targetNamespace = "http://tempuri.org/") String pXmlSolicitud,
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token);

	/**
	 * Alta de Documentos
	 * 
	 * @param reciboNombreEmpleado
	 * @param claseRecibo
	 * @param reciboNombreEmpleador
	 * @param cuit
	 * @param reciboE
	 * @param reciboP
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/inboxAdd")
	@WebResult(name = "inboxAddResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "inboxAdd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InboxAdd")
	@ResponseWrapper(localName = "inboxAddResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InboxAddResponse")
	public String inboxAdd(@WebParam(name = "reciboE", targetNamespace = "http://tempuri.org/") String reciboE,
			@WebParam(name = "reciboP", targetNamespace = "http://tempuri.org/") String reciboP,
			@WebParam(name = "reciboNombreEmpleado", targetNamespace = "http://tempuri.org/") String reciboNombreEmpleado,
			@WebParam(name = "reciboNombreEmpleador", targetNamespace = "http://tempuri.org/") String reciboNombreEmpleador,
			@WebParam(name = "claseRecibo", targetNamespace = "http://tempuri.org/") String claseRecibo,
			@WebParam(name = "cuit", targetNamespace = "http://tempuri.org/") String cuit,
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token);

	/**
	 * Alta de documentos
	 * 
	 * @param recibo
	 * @param reciboNombre
	 * @param claseRecibo
	 * @param cuit
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/inboxAddDocument")
	@WebResult(name = "inboxAddDocumentResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "inboxAddDocument", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InboxAddDocument")
	@ResponseWrapper(localName = "inboxAddDocumentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InboxAddDocumentResponse")
	public String inboxAddDocument(@WebParam(name = "recibo", targetNamespace = "http://tempuri.org/") String recibo,
			@WebParam(name = "reciboNombre", targetNamespace = "http://tempuri.org/") String reciboNombre,
			@WebParam(name = "claseRecibo", targetNamespace = "http://tempuri.org/") String claseRecibo,
			@WebParam(name = "cuit", targetNamespace = "http://tempuri.org/") String cuit,
			@WebParam(name = "Token", targetNamespace = "http://tempuri.org/") String token);

	/**
	 * Baja de Empleados
	 * 
	 * @param borrar
	 * @param cuit
	 * @param cuil
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/employeeDelete")
	@WebResult(name = "employeeDeleteResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "employeeDelete", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmployeeDelete")
	@ResponseWrapper(localName = "employeeDeleteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmployeeDeleteResponse")
	public String employeeDelete(@WebParam(name = "cuil", targetNamespace = "http://tempuri.org/") String cuil,
			@WebParam(name = "cuit", targetNamespace = "http://tempuri.org/") String cuit,
			@WebParam(name = "borrar", targetNamespace = "http://tempuri.org/") boolean borrar,
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token);

	/**
	 * Solicitud de Certificado Digital
	 * 
	 * @param xmlSolicitud
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/enviarSolicitud")
	@WebResult(name = "enviarSolicitudResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "enviarSolicitud", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarSolicitud")
	@ResponseWrapper(localName = "enviarSolicitudResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviarSolicitudResponse")
	public String enviarSolicitud(
			@WebParam(name = "_xmlSolicitud", targetNamespace = "http://tempuri.org/") String xmlSolicitud,
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token);

	/**
	 * 
	 * @param xmlData
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "MobileInvoker", action = "http://tempuri.org/MobileInvoker")
	@WebResult(name = "MobileInvokerResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "MobileInvoker", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MobileInvoker")
	@ResponseWrapper(localName = "MobileInvokerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MobileInvokerResponse")
	public String mobileInvoker(@WebParam(name = "xmlData", targetNamespace = "http://tempuri.org/") String xmlData);

	/**
	 * Inicio de sesi�n
	 * 
	 * @param password
	 * @param idCompany
	 * @param nombreUsuario
	 * @param passwordAD
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/login")
	@WebResult(name = "loginResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
	public String login(
			@WebParam(name = "nombre_usuario", targetNamespace = "http://tempuri.org/") String nombreUsuario,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "passwordAD", targetNamespace = "http://tempuri.org/") String passwordAD,
			@WebParam(name = "idCompany", targetNamespace = "http://tempuri.org/") String idCompany);

	/**
	 * Cierre de sesi�n
	 * 
	 * @param token
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/logout")
	@WebResult(name = "logoutResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "logout", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Logout")
	@ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutResponse")
	public String logout(@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token);

}
